global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: node_exporter_iac
    static_configs:
      - targets:
          - salt-master:9100
          - salt-minion-qg-1:9100
          - salt-minion-qg-2:9100
          - ansible-panelpc:9100
          - ansible-worker-qg-1:9100
          - ansible-worker-qg-2:9100

  - job_name: salt_exporter
    static_configs:
      - targets:
          - salt-master:9191

  - job_name: pushgateway
    static_configs:
      - targets:
          - pushgateway:9091
