---
- name: Install gnome-boxes
  hosts: control
  become: true
  gather_facts: true
  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
        # Trigger force refresh
        cache_valid_time: 0

    - name: Install gnome-boxes packages
      ansible.builtin.package:
        name: "gnome-boxes"
        state: present